# Generated by Django 2.0.5 on 2018-05-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NerString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_text', models.CharField(max_length=200)),
                ('ne_start_char', models.PositiveSmallIntegerField()),
                ('ne_end_char', models.PositiveSmallIntegerField()),
                ('ne_type', models.CharField(max_length=200)),
                ('status', models.PositiveSmallIntegerField()),
                ('last_edit', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
